sudo: required
language: node_js
node_js:
    - "stable"
    - "5.5"
    - "4"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-vir-test
        packages:
            - g++-4.8
before_install:
    npm install -g mocha
services:
    - mongodb

