language: node_js

node_js:
    - 7.0
env:
    - CXX=g++-4.8
    - NODE_ENV=production
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
before_install:
  - npm install -g mocha
script:
  - npm test
