language: node_js

node_js:
    - 7.1
env:
    - CXX=g++-4.8 NODE_ENV=production
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
script:
  - npm test

after_success:
    - bash <(curl -s https://codecov.io/bash)

