sudo: false

language: node_js

node_js:
    - "stable"
    - "6.2.2"

compiler: clang-3.6

env:
    - CXX=clang-3.6

before_install:
    - npm install -g mocha
    - gem install sass

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
            - g++-4.8

services:
    - mongodb
    - redis-server
